#!/usr/bin/env python3
"""
prompts 包初始化文件
"""

from .task_recognizer_prompt import (
    TASK_RECOGNITION_PROMPT,
    PHONE_AGENT_EXTRACT_PROMPT,
    MULTIMODAL_TASK_PROMPT
)

from .agent_executor_prompt import CHAT_MESSAGE_PROMPT

from .reply_manager_prompt import (
    EXTRACT_PROMPT,
    PARSE_MESSAGES_PROMPT,
    EXTRACT_CHAT_RECORDS_PROMPT,
    GENERATE_REPLY_PROMPT,
    GENERATE_REPLY_SYSTEM_PROMPT
)

__all__ = [
    'TASK_RECOGNITION_PROMPT',
    'PHONE_AGENT_EXTRACT_PROMPT',
    'MULTIMODAL_TASK_PROMPT',
    'CHAT_MESSAGE_PROMPT',
    'EXTRACT_PROMPT',
    'PARSE_MESSAGES_PROMPT',
    'EXTRACT_CHAT_RECORDS_PROMPT',
    'GENERATE_REPLY_PROMPT',
    'GENERATE_REPLY_SYSTEM_PROMPT',
]
