"""
提示词模块
"""
from .judgement_prompt import (
    TASK_JUDGEMENT_PROMPT,
    TASK_TYPE_FREE_CHAT,
    TASK_TYPE_BASIC_OPERATION,
    TASK_TYPE_SINGLE_REPLY,
    TASK_TYPE_CONTINUOUS_REPLY,
    TASK_TYPE_COMPLEX_OPERATION,
)
from .chat_prompt import (
    CHAT_SYSTEM_PROMPT,
    CHAT_WITH_CONTEXT_PROMPT,
    CHAT_BUILD_SYSTEM_PROMPT_BASE,
    CHAT_TIME_INSTRUCTION,
    CHAT_FINAL_INSTRUCTION,
)
from .phone_prompt import (
    PHONE_OPERATION_PROMPT,
    PHONE_EXTRACT_CHAT_PROMPT,
    PHONE_SEND_MESSAGE_PROMPT,
    PHONE_EXTRACT_TASK_PROMPT,
    PHONE_SEND_TASK_QQ,
    PHONE_SEND_TASK_WECHAT,
    PHONE_SEND_TASK_DEFAULT,
)
from .reply_prompt import (
    REPLY_GENERATION_PROMPT,
    REPLY_JUDGEMENT_PROMPT,
    REPLY_NODE_SYSTEM_PROMPT,
    REPLY_NODE_USER_PROMPT,
)
from .parse_prompt import (
    PARSE_MESSAGES_SYSTEM_PROMPT,
    PARSE_MESSAGES_PROMPT,
    PARSE_MESSAGES_MAX_LENGTH,
)

__all__ = [
    "TASK_JUDGEMENT_PROMPT",
    "TASK_TYPE_FREE_CHAT",
    "TASK_TYPE_BASIC_OPERATION",
    "TASK_TYPE_SINGLE_REPLY",
    "TASK_TYPE_CONTINUOUS_REPLY",
    "TASK_TYPE_COMPLEX_OPERATION",
    "CHAT_SYSTEM_PROMPT",
    "CHAT_WITH_CONTEXT_PROMPT",
    "CHAT_BUILD_SYSTEM_PROMPT_BASE",
    "CHAT_TIME_INSTRUCTION",
    "CHAT_FINAL_INSTRUCTION",
    "PHONE_OPERATION_PROMPT",
    "PHONE_EXTRACT_CHAT_PROMPT",
    "PHONE_SEND_MESSAGE_PROMPT",
    "PHONE_EXTRACT_TASK_PROMPT",
    "PHONE_SEND_TASK_QQ",
    "PHONE_SEND_TASK_WECHAT",
    "PHONE_SEND_TASK_DEFAULT",
    "REPLY_GENERATION_PROMPT",
    "REPLY_JUDGEMENT_PROMPT",
    "REPLY_NODE_SYSTEM_PROMPT",
    "REPLY_NODE_USER_PROMPT",
    "PARSE_MESSAGES_SYSTEM_PROMPT",
    "PARSE_MESSAGES_PROMPT",
    "PARSE_MESSAGES_MAX_LENGTH",
]
